!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
! MODEL
!	   BFM - Biogeochemical Flux Model
!
! MODULE
!   set_var_info_bfm
!
! FILE
!   set_var_info_bfm
!
! DESCRIPTION
!  This subroutine provides information on the variables. To be used
!  when storing data in NetCDF files.
!  This file is produced by a procedure from a file which include all
!  definitions of global variables and state variables  and a proto-file 
!
!
! AUTHORS
!    Piet Ruardij
!
! CHANGE_LOG
!   ---
!
! COPYING
!   
!   Copyright (C) 2013 BFM System Team (bfm_st@lists.cmcc.it)
!   Copyright (C) 2006 P. Ruardij  (rua@nioz.nl)
!
!   This program is free software; you can redistribute it and/or modify
!   it under the terms of the GNU General Public License as published by
!   the Free Software Foundation;
!   This program is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTEABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!   GNU General Public License for more details.
!
!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
!
!
!

subroutine set_var_info_bfm

#ifdef BFM_GOTM
  use mem
  use bio_var, only: var_names,var_long,var_units
  use bio_var, only: stPelStateS,stPelDiagS,stPelFluxS,stBenStateS,stBenDiagS,stBenFluxS
  use bio_var, only: stPelStateE,stPelDiagE,stPelFluxE,stBenStateE,stBenDiagE,stBenFluxE
#else
  use api_bfm
#endif
 

!
! 3d variables description:
!
   var_names(1)="O2o"
   var_long(1)="Oxygen"
   var_units(1)="mmol O2/m3"
   var_names(2)="N1p"
   var_long(2)="Phosphate"
   var_units(2)="mmol P/m3"
   var_names(3)="N3n"
   var_long(3)="Nitrate"
   var_units(3)="mmol N/m3"
   var_names(4)="N4n"
   var_long(4)="Ammonium"
   var_units(4)="mmol N/m3"
   var_names(5)="O4n"
   var_long(5)="NitrogenSink"
   var_units(5)="mmol N/m3"
   var_names(6)="N5s"
   var_long(6)="Silicate"
   var_units(6)="mmol Si/m3"
   var_names(7)="N6r"
   var_long(7)="Reduction Equivalents"
   var_units(7)="mmol S--/m3"
   var_names(8)="B1c"
   var_long(8)="Aerobic and Anaerobic Bacteria"
   var_units(8)="mg C/m3"
   var_names(9)="B1n"
   var_long(9)="Aerobic and Anaerobic Bacteria"
   var_units(9)="mmol N/m3"
   var_names(10)="B1p"
   var_long(10)="Aerobic and Anaerobic Bacteria"
   var_units(10)="mmol P/m3"
   var_names(11)="P1c"
   var_long(11)="Diatoms"
   var_units(11)="mg C/m3"
   var_names(12)="P1n"
   var_long(12)="Diatoms"
   var_units(12)="mmol N/m3"
   var_names(13)="P1p"
   var_long(13)="Diatoms"
   var_units(13)="mmol P/m3"
   var_names(14)="P1l"
   var_long(14)="Diatoms"
   var_units(14)="mg Chl/m3"
   var_names(15)="P1s"
   var_long(15)="Diatoms"
   var_units(15)="mmol Si/m3"
   var_names(16)="P2c"
   var_long(16)="Flagellates"
   var_units(16)="mg C/m3"
   var_names(17)="P2n"
   var_long(17)="Flagellates"
   var_units(17)="mmol N/m3"
   var_names(18)="P2p"
   var_long(18)="Flagellates"
   var_units(18)="mmol P/m3"
   var_names(19)="P2l"
   var_long(19)="Flagellates"
   var_units(19)="mg Chl/m3"
   var_names(20)="P3c"
   var_long(20)="PicoPhytoplankton"
   var_units(20)="mg C/m3"
   var_names(21)="P3n"
   var_long(21)="PicoPhytoplankton"
   var_units(21)="mmol N/m3"
   var_names(22)="P3p"
   var_long(22)="PicoPhytoplankton"
   var_units(22)="mmol P/m3"
   var_names(23)="P3l"
   var_long(23)="PicoPhytoplankton"
   var_units(23)="mg Chl/m3"
   var_names(24)="P4c"
   var_long(24)="Large Phytoplankton"
   var_units(24)="mg C/m3"
   var_names(25)="P4n"
   var_long(25)="Large Phytoplankton"
   var_units(25)="mmol N/m3"
   var_names(26)="P4p"
   var_long(26)="Large Phytoplankton"
   var_units(26)="mmol P/m3"
   var_names(27)="P4l"
   var_long(27)="Large Phytoplankton"
   var_units(27)="mg Chl/m3"
   var_names(28)="Z3c"
   var_long(28)="Carnivorous Mesozooplankton"
   var_units(28)="mg C/m3"
   var_names(29)="Z3n"
   var_long(29)="Carnivorous Mesozooplankton"
   var_units(29)="mmol N/m3"
   var_names(30)="Z3p"
   var_long(30)="Carnivorous Mesozooplankton"
   var_units(30)="mmol P/m3"
   var_names(31)="Z4c"
   var_long(31)="Omnivorous Mesozooplankton"
   var_units(31)="mg C/m3"
   var_names(32)="Z4n"
   var_long(32)="Omnivorous Mesozooplankton"
   var_units(32)="mmol N/m3"
   var_names(33)="Z4p"
   var_long(33)="Omnivorous Mesozooplankton"
   var_units(33)="mmol P/m3"
   var_names(34)="Z5c"
   var_long(34)="Microzooplankton"
   var_units(34)="mg C/m3"
   var_names(35)="Z5n"
   var_long(35)="Microzooplankton"
   var_units(35)="mmol N/m3"
   var_names(36)="Z5p"
   var_long(36)="Microzooplankton"
   var_units(36)="mmol P/m3"
   var_names(37)="Z6c"
   var_long(37)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(37)="mg C/m3"
   var_names(38)="Z6n"
   var_long(38)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(38)="mmol N/m3"
   var_names(39)="Z6p"
   var_long(39)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(39)="mmol P/m3"
   var_names(40)="R1c"
   var_long(40)="Labile Dissolved Organic Matter"
   var_units(40)="mg C/m3"
   var_names(41)="R1n"
   var_long(41)="Labile Dissolved Organic Matter"
   var_units(41)="mmol N/m3"
   var_names(42)="R1p"
   var_long(42)="Labile Dissolved Organic Matter"
   var_units(42)="mmol P/m3"
   var_names(43)="R2c"
   var_long(43)="Semi-labile Dissolved Organic Carbon"
   var_units(43)="mg C/m3"
   var_names(44)="R3c"
   var_long(44)="Semi-refractory Dissolved Organic Carbon"
   var_units(44)="mg C/m3"
   var_names(45)="R6c"
   var_long(45)="Particulate Organic Matter"
   var_units(45)="mg C/m3"
   var_names(46)="R6n"
   var_long(46)="Particulate Organic Matter"
   var_units(46)="mmol N/m3"
   var_names(47)="R6p"
   var_long(47)="Particulate Organic Matter"
   var_units(47)="mmol P/m3"
   var_names(48)="R6s"
   var_long(48)="Particulate Organic Matter"
   var_units(48)="mmol Si/m3"
   var_names(49)="O3c"
   var_long(49)="Dissolved Inorganic Carbon"
   var_units(49)="mg C/m3"
   var_names(50)="O3h"
   var_long(50)="Dissolved Inorganic Carbon"
   var_units(50)="mmol eq/m3"

   var_names(51)="ETW"
   var_long(51)="temperature"
   var_units(51)="C"
   var_names(52)="ESW"
   var_long(52)="Salinity"
   var_units(52)="-"
   var_names(53)="ERHO"
   var_long(53)="Seawater Density"
   var_units(53)="kg/m3"
   var_names(54)="EIR"
   var_long(54)="Irradiance"
   var_units(54)="uE/m2/s"
   var_names(55)="ESS"
   var_long(55)="Suspended Sediments"
   var_units(55)="g/m3"
   var_names(56)="exud"
   var_long(56)="exudation"
   var_units(56)="mg C/m3"
   var_names(57)="Depth"
   var_long(57)="Gridpoint Depth"
   var_units(57)="m"
   var_names(58)="Volume"
   var_long(58)="Gridpoint Volume"
   var_units(58)="m3"
   var_names(59)="Area"
   var_long(59)="Gridpoint Area"
   var_units(59)="m2"
   var_names(60)="DIC"
   var_long(60)="Dissolved Inorganic Carbon"
   var_units(60)="umol/kg"
   var_names(61)="CO2"
   var_long(61)="CO2(aq)"
   var_units(61)="umol/kg"
   var_names(62)="pCO2"
   var_long(62)="Oceanic pCO2"
   var_units(62)="uatm"
   var_names(63)="HCO3"
   var_long(63)="Bicarbonate"
   var_units(63)="umol/kg"
   var_names(64)="CO3"
   var_long(64)="Carbonate"
   var_units(64)="umol/kg"
   var_names(65)="ALK"
   var_long(65)="Alkalinity"
   var_units(65)="umol eq/kg"
   var_names(66)="pH"
   var_long(66)="pH"
   var_units(66)="-"
   var_names(67)="OCalc"
   var_long(67)="Saturation state of Calcite"
   var_units(67)="-"
   var_names(68)="OArag"
   var_long(68)="Saturation state of Aragonite"
   var_units(68)="-"
   var_names(69)="EPR"
   var_long(69)="Water Pressure"
   var_units(69)="dbar"
   var_names(70)="totpelc"
   var_long(70)="Total Mass in Pelagic"
   var_units(70)="g C"
   var_names(71)="totpeln"
   var_long(71)="Total Mass in Pelagic"
   var_units(71)="g N"
   var_names(72)="totpelp"
   var_long(72)="Total Mass in Pelagic"
   var_units(72)="g P"
   var_names(73)="totpels"
   var_long(73)="Total Mass in Pelagic"
   var_units(73)="g Si"
   var_names(74)="cxoO2"
   var_long(74)="Oxygen Saturation"
   var_units(74)="mmol O2/m3"
   var_names(75)="eO2mO2"
   var_long(75)="Relative Oxygen saturation"
   var_units(75)="-"
   var_names(76)="Chla"
   var_long(76)="Chlorophyll-a"
   var_units(76)="mg Chl/m3"
   var_names(77)="flPTN6r"
   var_long(77)="Pelagic Anaerobic Mineralization Rate"
   var_units(77)="mmol O2/m3/d"
   var_names(78)="flN3O4n"
   var_long(78)="Pelagic Denitrification Rate"
   var_units(78)="mmol N/m3/d"
   var_names(79)="flN4N3n"
   var_long(79)="Pelagic Nitrification Rate"
   var_units(79)="mmol N/m3/d"
   var_names(80)="sediR2"
   var_long(80)="Detritus sedimentation rate"
   var_units(80)="m/d"
   var_names(81)="sediR6"
   var_long(81)="Detritus sedimentation rate"
   var_units(81)="m/d"
   var_names(82)="xEPS"
   var_long(82)="Total Extinction Coefficient"
   var_units(82)="1/m"
   var_names(83)="ABIO_eps"
   var_long(83)="Abiotic Extinction Coefficient"
   var_units(83)="1/m"

   var_names(84)="qpcPPY(iiP1)"
   var_long(84)="Quotum P/C in Phytoplankton"
   var_units(84)="mmol P/mg C"
   var_names(85)="qpcPPY(iiP2)"
   var_long(85)="Quotum P/C in Phytoplankton"
   var_units(85)="mmol P/mg C"
   var_names(86)="qpcPPY(iiP3)"
   var_long(86)="Quotum P/C in Phytoplankton"
   var_units(86)="mmol P/mg C"
   var_names(87)="qpcPPY(iiP4)"
   var_long(87)="Quotum P/C in Phytoplankton"
   var_units(87)="mmol P/mg C"
   var_names(88)="qncPPY(iiP1)"
   var_long(88)="Quotum N/C in Phytoplankton"
   var_units(88)="mmol N/mg C"
   var_names(89)="qncPPY(iiP2)"
   var_long(89)="Quotum N/C in Phytoplankton"
   var_units(89)="mmol N/mg C"
   var_names(90)="qncPPY(iiP3)"
   var_long(90)="Quotum N/C in Phytoplankton"
   var_units(90)="mmol N/mg C"
   var_names(91)="qncPPY(iiP4)"
   var_long(91)="Quotum N/C in Phytoplankton"
   var_units(91)="mmol N/mg C"
   var_names(92)="qscPPY(iiP1)"
   var_long(92)="Quotum Si/C in Phytoplankton"
   var_units(92)="mmol Si/mg C"
   var_names(93)="qscPPY(iiP2)"
   var_long(93)="Quotum Si/C in Phytoplankton"
   var_units(93)="mmol Si/mg C"
   var_names(94)="qscPPY(iiP3)"
   var_long(94)="Quotum Si/C in Phytoplankton"
   var_units(94)="mmol Si/mg C"
   var_names(95)="qscPPY(iiP4)"
   var_long(95)="Quotum Si/C in Phytoplankton"
   var_units(95)="mmol Si/mg C"
   var_names(96)="qlcPPY(iiP1)"
   var_long(96)="Quotum Chl/C in Phytoplankton"
   var_units(96)="mg Chl /mg C"
   var_names(97)="qlcPPY(iiP2)"
   var_long(97)="Quotum Chl/C in Phytoplankton"
   var_units(97)="mg Chl /mg C"
   var_names(98)="qlcPPY(iiP3)"
   var_long(98)="Quotum Chl/C in Phytoplankton"
   var_units(98)="mg Chl /mg C"
   var_names(99)="qlcPPY(iiP4)"
   var_long(99)="Quotum Chl/C in Phytoplankton"
   var_units(99)="mg Chl /mg C"
   var_names(100)="qpcMEZ(iiZ3)"
   var_long(100)="Quotum P/C in Mesozooplankton"
   var_units(100)="mmol P/mg C"
   var_names(101)="qpcMEZ(iiZ4)"
   var_long(101)="Quotum P/C in Mesozooplankton"
   var_units(101)="mmol P/mg C"
   var_names(102)="qncMEZ(iiZ3)"
   var_long(102)="Quotum N/C in Mesozooplankton"
   var_units(102)="mmol N/mg C"
   var_names(103)="qncMEZ(iiZ4)"
   var_long(103)="Quotum N/C in Mesozooplankton"
   var_units(103)="mmol N/mg C"
   var_names(104)="qpcMIZ(iiZ5)"
   var_long(104)="Quotum P/C in Z5(MicroZooPlankton)"
   var_units(104)="mmol P/mg C"
   var_names(105)="qpcMIZ(iiZ6)"
   var_long(105)="Quotum P/C in Z6(MicroZooPlankton)"
   var_units(105)="mmol P/mg C"
   var_names(106)="qncMIZ(iiZ5)"
   var_long(106)="Quotum N/C in Z5(MicroZooPlankton)"
   var_units(106)="mmol N/mg C"
   var_names(107)="qncMIZ(iiZ6)"
   var_long(107)="Quotum N/C in Z6(MicroZooPlankton)"
   var_units(107)="mmol N/mg C"
   var_names(108)="qpcOMT(iiR1)"
   var_long(108)="Quotum P/C in Organic Matter"
   var_units(108)="mmol N/mg C"
   var_names(109)="qpcOMT(iiR2)"
   var_long(109)="Quotum P/C in Organic Matter"
   var_units(109)="mmol N/mg C"
   var_names(110)="qpcOMT(iiR3)"
   var_long(110)="Quotum P/C in Organic Matter"
   var_units(110)="mmol N/mg C"
   var_names(111)="qpcOMT(iiR6)"
   var_long(111)="Quotum P/C in Organic Matter"
   var_units(111)="mmol N/mg C"
   var_names(112)="qncOMT(iiR1)"
   var_long(112)="Quotum N/C in Organic Matter"
   var_units(112)="mmol P/mg C"
   var_names(113)="qncOMT(iiR2)"
   var_long(113)="Quotum N/C in Organic Matter"
   var_units(113)="mmol P/mg C"
   var_names(114)="qncOMT(iiR3)"
   var_long(114)="Quotum N/C in Organic Matter"
   var_units(114)="mmol P/mg C"
   var_names(115)="qncOMT(iiR6)"
   var_long(115)="Quotum N/C in Organic Matter"
   var_units(115)="mmol P/mg C"
   var_names(116)="qscOMT(iiR1)"
   var_long(116)="Quotum Si/C in Organic Matter"
   var_units(116)="mmol Si/mg C"
   var_names(117)="qscOMT(iiR2)"
   var_long(117)="Quotum Si/C in Organic Matter"
   var_units(117)="mmol Si/mg C"
   var_names(118)="qscOMT(iiR3)"
   var_long(118)="Quotum Si/C in Organic Matter"
   var_units(118)="mmol Si/mg C"
   var_names(119)="qscOMT(iiR6)"
   var_long(119)="Quotum Si/C in Organic Matter"
   var_units(119)="mmol Si/mg C"
   var_names(120)="qpcPBA(iiB1)"
   var_long(120)="Quotum P/C in Pelagic Bacteria"
   var_units(120)="mmol P/mg C"
   var_names(121)="qncPBA(iiB1)"
   var_long(121)="Quotum N/C in Pelagic Bacteria"
   var_units(121)="mmol N/mg C"
   var_names(122)="sediPPY(iiP1)"
   var_long(122)="P1(PhytoPlankton) sedimentation rate"
   var_units(122)="m/d"
   var_names(123)="sediPPY(iiP2)"
   var_long(123)="P2(PhytoPlankton) sedimentation rate"
   var_units(123)="m/d"
   var_names(124)="sediPPY(iiP3)"
   var_long(124)="P3(PhytoPlankton) sedimentation rate"
   var_units(124)="m/d"
   var_names(125)="sediPPY(iiP4)"
   var_long(125)="P4(PhytoPlankton) sedimentation rate"
   var_units(125)="m/d"
   var_names(126)="sediMIZ(iiZ5)"
   var_long(126)="Z5(MicroZooPlankton) sedimentation rate"
   var_units(126)="m/d"
   var_names(127)="sediMIZ(iiZ6)"
   var_long(127)="Z6(MicroZooPlankton) sedimentation rate"
   var_units(127)="m/d"
   var_names(128)="sediMEZ(iiZ3)"
   var_long(128)="Z3(MesoZooPlankton) sedimentation rate"
   var_units(128)="m/d"
   var_names(129)="sediMEZ(iiZ4)"
   var_long(129)="Z4(MesoZooPlankton) sedimentation rate"
   var_units(129)="m/d"
   var_names(130)="sunPPY(iiP1)"
   var_long(130)="Specific Net Production of P1(PhytoPlankton)"
   var_units(130)="1/d"
   var_names(131)="sunPPY(iiP2)"
   var_long(131)="Specific Net Production of P2(PhytoPlankton)"
   var_units(131)="1/d"
   var_names(132)="sunPPY(iiP3)"
   var_long(132)="Specific Net Production of P3(PhytoPlankton)"
   var_units(132)="1/d"
   var_names(133)="sunPPY(iiP4)"
   var_long(133)="Specific Net Production of P4(PhytoPlankton)"
   var_units(133)="1/d"
   var_names(134)="eiPPY(iiP1)"
   var_long(134)="Regulating Factor for Light in P1(PhytoPlankton)"
   var_units(134)="-"
   var_names(135)="eiPPY(iiP2)"
   var_long(135)="Regulating Factor for Light in P2(PhytoPlankton)"
   var_units(135)="-"
   var_names(136)="eiPPY(iiP3)"
   var_long(136)="Regulating Factor for Light in P3(PhytoPlankton)"
   var_units(136)="-"
   var_names(137)="eiPPY(iiP4)"
   var_long(137)="Regulating Factor for Light in P4(PhytoPlankton)"
   var_units(137)="-"
   var_names(138)="ELiPPY(iiP1)"
   var_long(138)="Optimal light in P1(PhytoPlankton)"
   var_units(138)="W/m2"
   var_names(139)="ELiPPY(iiP2)"
   var_long(139)="Optimal light in P2(PhytoPlankton)"
   var_units(139)="W/m2"
   var_names(140)="ELiPPY(iiP3)"
   var_long(140)="Optimal light in P3(PhytoPlankton)"
   var_units(140)="W/m2"
   var_names(141)="ELiPPY(iiP4)"
   var_long(141)="Optimal light in P4(PhytoPlankton)"
   var_units(141)="W/m2"

   var_names(142)="fP1Z4c"
   var_long(142)="diatom grazing by omniv.zooplankton"
   var_units(142)="mg C/m3/d"
   var_names(143)="fP2Z4c"
   var_long(143)="flagellates grazing by omniv.zooplankton"
   var_units(143)="mg C/m3/d"
   var_names(144)="fP3Z4c"
   var_long(144)="picophytoplankton grazing by omniv.zooplankton"
   var_units(144)="mg C/m3/d"
   var_names(145)="fP4Z4c"
   var_long(145)="large phytoplankton grazing by omniv.zooplankton"
   var_units(145)="mg C/m3/d"
   var_names(146)="fP1Z5c"
   var_long(146)="diatom grazing by microzooplankton"
   var_units(146)="mg C/m3/d"
   var_names(147)="fP2Z5c"
   var_long(147)="flagellates grazing by microzooplankton"
   var_units(147)="mg C/m3/d"
   var_names(148)="fP3Z5c"
   var_long(148)="picophytoplankton grazing by microzooplankton"
   var_units(148)="mg C/m3/d"
   var_names(149)="fP4Z5c"
   var_long(149)="large phytoplankton grazing by microzooplankton"
   var_units(149)="mg C/m3/d"
   var_names(150)="fP1Z6c"
   var_long(150)="diatom grazing by heterotrophic nanoflagellates"
   var_units(150)="mg C/m3/d"
   var_names(151)="fP2Z6c"
   var_long(151)="flagellates grazing by heterotrophic nanoflagellates"
   var_units(151)="mg C/m3/d"
   var_names(152)="fP3Z6c"
   var_long(152)="picophytoplankton grazing by heterotrophic nanoflagellates"
   var_units(152)="mg C/m3/d"
   var_names(153)="fP4Z6c"
   var_long(153)="large phytoplankton grazing by heterotrophic nanoflagellates"
   var_units(153)="mg C/m3/d"
   var_names(154)="fB1Z6c"
   var_long(154)="bacterial grazing by heterotrophic nanoflagellates"
   var_units(154)="mg C/m3/d"
   var_names(155)="fB1Z5c"
   var_long(155)="bacterial grazing by microzooplankton"
   var_units(155)="mg C/m3/d"
   var_names(156)="ruPTc"
   var_long(156)="Gross Primary Production"
   var_units(156)="mg C/m3/d"
   var_names(157)="resPP"
   var_long(157)="Respiration of phytoplankton"
   var_units(157)="mg C/m3/d"
   var_names(158)="resZT"
   var_long(158)="Respiration of zooplankton"
   var_units(158)="mg C/m3/d"
   var_names(159)="ruPTn"
   var_long(159)="net nutrient uptake"
   var_units(159)="mmoln /m3/d"
   var_names(160)="ruPTp"
   var_long(160)="net phosphate uptake"
   var_units(160)="mmol P /m3/d"
   var_names(161)="exPP"
   var_long(161)="C excretion from phytoplankton"
   var_units(161)="mg C/m3/d"
   var_names(162)="ruZTc"
   var_long(162)="gross secondary production"
   var_units(162)="mg C/m3/d"
   var_names(163)="netZTc"
   var_long(163)="net secondary production"
   var_units(163)="mg C/m3/d"
   var_names(164)="rrPTo"
   var_long(164)="pelagic respiration"
   var_units(164)="mmol O2/m3/d"
   var_names(165)="rePTn"
   var_long(165)="pelagic mineralization"
   var_units(165)="mmol N/m3/d"
   var_names(166)="rePTp"
   var_long(166)="pelagic mineralization"
   var_units(166)="mmol P /m3/d"
   var_names(167)="reBn"
   var_long(167)="bacterial mineralization"
   var_units(167)="mmol N/m3/d"
   var_names(168)="ruBn"
   var_long(168)="bacterial uptake"
   var_units(168)="mmol N/m3/d"
   var_names(169)="reBp"
   var_long(169)="bacterial mineralization"
   var_units(169)="mmol P/m3/d"
   var_names(170)="ruBp"
   var_long(170)="bacterial uptake"
   var_units(170)="mmol P/m3/d"
   var_names(171)="fR2B1c"
   var_long(171)="TEP uptake by bacteria"
   var_units(171)="mg C/m3/d"


!
!2d Pelagic variables description
   var_names(172)="ETAUB"
   var_long(172)="Bottom Stress"
   var_units(172)="N m/s"
   var_names(173)="EPCO2air"
   var_long(173)="Atmospheric CO2 Partial Pressure"
   var_units(173)="uatm"
   var_names(174)="CO2airflux"
   var_long(174)="Sea-air CO2 Flux"
   var_units(174)="mmol/m2/d"
   var_names(175)="Area2d"
   var_long(175)="2-D Gridpoint Area"
   var_units(175)="m2"
   var_names(176)="ThereIsLight"
   var_long(176)="Switch for day/night cycle"
   var_units(176)="-"
   var_names(177)="SUNQ"
   var_long(177)="Daylength in hours"
   var_units(177)="h"
   var_names(178)="EWIND"
   var_long(178)="Wind speed"
   var_units(178)="m/s"
   var_names(179)="totsysc"
   var_long(179)="total mass"
   var_units(179)="g C"
   var_names(180)="totsysn"
   var_long(180)="total mass"
   var_units(180)="g N"
   var_names(181)="totsysp"
   var_long(181)="total mass"
   var_units(181)="g P"
   var_names(182)="totsyss"
   var_long(182)="total mass"
   var_units(182)="g Si"
   var_names(183)="EICE"
   var_long(183)="Sea-ice fraction"
   var_units(183)="-"

!
! surface
!
   var_names(184)="jsurO2o"
   var_long(184)="flux of Oxygen at SURFACE"
   var_units(184)="mmol O2/m2/day"
   var_names(185)="jsurN1p"
   var_long(185)="flux of Phosphate at SURFACE"
   var_units(185)="mmol P/m2/day"
   var_names(186)="jsurN3n"
   var_long(186)="flux of Nitrate at SURFACE"
   var_units(186)="mmol N/m2/day"
   var_names(187)="jsurN4n"
   var_long(187)="flux of Ammonium at SURFACE"
   var_units(187)="mmol N/m2/day"
   var_names(188)="jsurO4n"
   var_long(188)="flux of NitrogenSink at SURFACE"
   var_units(188)="mmol N/m2/day"
   var_names(189)="jsurN5s"
   var_long(189)="flux of Silicate at SURFACE"
   var_units(189)="mmol Si/m2/day"
   var_names(190)="jsurN6r"
   var_long(190)="flux of Reduction Equivalents at SURFACE"
   var_units(190)="mmol S--/m2/day"
   var_names(191)="jsurB1c"
   var_long(191)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(191)="mg C/m2/day"
   var_names(192)="jsurB1n"
   var_long(192)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(192)="mmol N/m2/day"
   var_names(193)="jsurB1p"
   var_long(193)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(193)="mmol P/m2/day"
   var_names(194)="jsurP1c"
   var_long(194)="flux of Diatoms at SURFACE"
   var_units(194)="mg C/m2/day"
   var_names(195)="jsurP1n"
   var_long(195)="flux of Diatoms at SURFACE"
   var_units(195)="mmol N/m2/day"
   var_names(196)="jsurP1p"
   var_long(196)="flux of Diatoms at SURFACE"
   var_units(196)="mmol P/m2/day"
   var_names(197)="jsurP1l"
   var_long(197)="flux of Diatoms at SURFACE"
   var_units(197)="mg Chl/m2/day"
   var_names(198)="jsurP1s"
   var_long(198)="flux of Diatoms at SURFACE"
   var_units(198)="mmol Si/m2/day"
   var_names(199)="jsurP2c"
   var_long(199)="flux of Flagellates at SURFACE"
   var_units(199)="mg C/m2/day"
   var_names(200)="jsurP2n"
   var_long(200)="flux of Flagellates at SURFACE"
   var_units(200)="mmol N/m2/day"
   var_names(201)="jsurP2p"
   var_long(201)="flux of Flagellates at SURFACE"
   var_units(201)="mmol P/m2/day"
   var_names(202)="jsurP2l"
   var_long(202)="flux of Flagellates at SURFACE"
   var_units(202)="mg Chl/m2/day"
   var_names(203)="jsurP3c"
   var_long(203)="flux of PicoPhytoplankton at SURFACE"
   var_units(203)="mg C/m2/day"
   var_names(204)="jsurP3n"
   var_long(204)="flux of PicoPhytoplankton at SURFACE"
   var_units(204)="mmol N/m2/day"
   var_names(205)="jsurP3p"
   var_long(205)="flux of PicoPhytoplankton at SURFACE"
   var_units(205)="mmol P/m2/day"
   var_names(206)="jsurP3l"
   var_long(206)="flux of PicoPhytoplankton at SURFACE"
   var_units(206)="mg Chl/m2/day"
   var_names(207)="jsurP4c"
   var_long(207)="flux of Large Phytoplankton at SURFACE"
   var_units(207)="mg C/m2/day"
   var_names(208)="jsurP4n"
   var_long(208)="flux of Large Phytoplankton at SURFACE"
   var_units(208)="mmol N/m2/day"
   var_names(209)="jsurP4p"
   var_long(209)="flux of Large Phytoplankton at SURFACE"
   var_units(209)="mmol P/m2/day"
   var_names(210)="jsurP4l"
   var_long(210)="flux of Large Phytoplankton at SURFACE"
   var_units(210)="mg Chl/m2/day"
   var_names(211)="jsurZ3c"
   var_long(211)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(211)="mg C/m2/day"
   var_names(212)="jsurZ3n"
   var_long(212)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(212)="mmol N/m2/day"
   var_names(213)="jsurZ3p"
   var_long(213)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(213)="mmol P/m2/day"
   var_names(214)="jsurZ4c"
   var_long(214)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(214)="mg C/m2/day"
   var_names(215)="jsurZ4n"
   var_long(215)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(215)="mmol N/m2/day"
   var_names(216)="jsurZ4p"
   var_long(216)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(216)="mmol P/m2/day"
   var_names(217)="jsurZ5c"
   var_long(217)="flux of Microzooplankton at SURFACE"
   var_units(217)="mg C/m2/day"
   var_names(218)="jsurZ5n"
   var_long(218)="flux of Microzooplankton at SURFACE"
   var_units(218)="mmol N/m2/day"
   var_names(219)="jsurZ5p"
   var_long(219)="flux of Microzooplankton at SURFACE"
   var_units(219)="mmol P/m2/day"
   var_names(220)="jsurZ6c"
   var_long(220)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(220)="mg C/m2/day"
   var_names(221)="jsurZ6n"
   var_long(221)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(221)="mmol N/m2/day"
   var_names(222)="jsurZ6p"
   var_long(222)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(222)="mmol P/m2/day"
   var_names(223)="jsurR1c"
   var_long(223)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(223)="mg C/m2/day"
   var_names(224)="jsurR1n"
   var_long(224)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(224)="mmol N/m2/day"
   var_names(225)="jsurR1p"
   var_long(225)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(225)="mmol P/m2/day"
   var_names(226)="jsurR2c"
   var_long(226)="flux of Semi-labile Dissolved Organic Carbon at SURFACE"
   var_units(226)="mg C/m2/day"
   var_names(227)="jsurR3c"
   var_long(227)="flux of Semi-refractory Dissolved Organic Carbon at SURFACE"
   var_units(227)="mg C/m2/day"
   var_names(228)="jsurR6c"
   var_long(228)="flux of Particulate Organic Matter at SURFACE"
   var_units(228)="mg C/m2/day"
   var_names(229)="jsurR6n"
   var_long(229)="flux of Particulate Organic Matter at SURFACE"
   var_units(229)="mmol N/m2/day"
   var_names(230)="jsurR6p"
   var_long(230)="flux of Particulate Organic Matter at SURFACE"
   var_units(230)="mmol P/m2/day"
   var_names(231)="jsurR6s"
   var_long(231)="flux of Particulate Organic Matter at SURFACE"
   var_units(231)="mmol Si/m2/day"
   var_names(232)="jsurO3c"
   var_long(232)="flux of Dissolved Inorganic Carbon at SURFACE"
   var_units(232)="mg C/m2/day"
   var_names(233)="jsurO3h"
   var_long(233)="flux of Dissolved Inorganic Carbon at SURFACE"
   var_units(233)="mmol eq/m2/day"

!
! bottom
!
   var_names(234)="jbotO2o"
   var_long(234)="flux of Oxygen at BOTTOM"
   var_units(234)="mmol O2/m2/day"
   var_names(235)="jbotN1p"
   var_long(235)="flux of Phosphate at BOTTOM"
   var_units(235)="mmol P/m2/day"
   var_names(236)="jbotN3n"
   var_long(236)="flux of Nitrate at BOTTOM"
   var_units(236)="mmol N/m2/day"
   var_names(237)="jbotN4n"
   var_long(237)="flux of Ammonium at BOTTOM"
   var_units(237)="mmol N/m2/day"
   var_names(238)="jbotO4n"
   var_long(238)="flux of NitrogenSink at BOTTOM"
   var_units(238)="mmol N/m2/day"
   var_names(239)="jbotN5s"
   var_long(239)="flux of Silicate at BOTTOM"
   var_units(239)="mmol Si/m2/day"
   var_names(240)="jbotN6r"
   var_long(240)="flux of Reduction Equivalents at BOTTOM"
   var_units(240)="mmol S--/m2/day"
   var_names(241)="jbotB1c"
   var_long(241)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(241)="mg C/m2/day"
   var_names(242)="jbotB1n"
   var_long(242)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(242)="mmol N/m2/day"
   var_names(243)="jbotB1p"
   var_long(243)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(243)="mmol P/m2/day"
   var_names(244)="jbotP1c"
   var_long(244)="flux of Diatoms at BOTTOM"
   var_units(244)="mg C/m2/day"
   var_names(245)="jbotP1n"
   var_long(245)="flux of Diatoms at BOTTOM"
   var_units(245)="mmol N/m2/day"
   var_names(246)="jbotP1p"
   var_long(246)="flux of Diatoms at BOTTOM"
   var_units(246)="mmol P/m2/day"
   var_names(247)="jbotP1l"
   var_long(247)="flux of Diatoms at BOTTOM"
   var_units(247)="mg Chl/m2/day"
   var_names(248)="jbotP1s"
   var_long(248)="flux of Diatoms at BOTTOM"
   var_units(248)="mmol Si/m2/day"
   var_names(249)="jbotP2c"
   var_long(249)="flux of Flagellates at BOTTOM"
   var_units(249)="mg C/m2/day"
   var_names(250)="jbotP2n"
   var_long(250)="flux of Flagellates at BOTTOM"
   var_units(250)="mmol N/m2/day"
   var_names(251)="jbotP2p"
   var_long(251)="flux of Flagellates at BOTTOM"
   var_units(251)="mmol P/m2/day"
   var_names(252)="jbotP2l"
   var_long(252)="flux of Flagellates at BOTTOM"
   var_units(252)="mg Chl/m2/day"
   var_names(253)="jbotP3c"
   var_long(253)="flux of PicoPhytoplankton at BOTTOM"
   var_units(253)="mg C/m2/day"
   var_names(254)="jbotP3n"
   var_long(254)="flux of PicoPhytoplankton at BOTTOM"
   var_units(254)="mmol N/m2/day"
   var_names(255)="jbotP3p"
   var_long(255)="flux of PicoPhytoplankton at BOTTOM"
   var_units(255)="mmol P/m2/day"
   var_names(256)="jbotP3l"
   var_long(256)="flux of PicoPhytoplankton at BOTTOM"
   var_units(256)="mg Chl/m2/day"
   var_names(257)="jbotP4c"
   var_long(257)="flux of Large Phytoplankton at BOTTOM"
   var_units(257)="mg C/m2/day"
   var_names(258)="jbotP4n"
   var_long(258)="flux of Large Phytoplankton at BOTTOM"
   var_units(258)="mmol N/m2/day"
   var_names(259)="jbotP4p"
   var_long(259)="flux of Large Phytoplankton at BOTTOM"
   var_units(259)="mmol P/m2/day"
   var_names(260)="jbotP4l"
   var_long(260)="flux of Large Phytoplankton at BOTTOM"
   var_units(260)="mg Chl/m2/day"
   var_names(261)="jbotZ3c"
   var_long(261)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(261)="mg C/m2/day"
   var_names(262)="jbotZ3n"
   var_long(262)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(262)="mmol N/m2/day"
   var_names(263)="jbotZ3p"
   var_long(263)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(263)="mmol P/m2/day"
   var_names(264)="jbotZ4c"
   var_long(264)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(264)="mg C/m2/day"
   var_names(265)="jbotZ4n"
   var_long(265)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(265)="mmol N/m2/day"
   var_names(266)="jbotZ4p"
   var_long(266)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(266)="mmol P/m2/day"
   var_names(267)="jbotZ5c"
   var_long(267)="flux of Microzooplankton at BOTTOM"
   var_units(267)="mg C/m2/day"
   var_names(268)="jbotZ5n"
   var_long(268)="flux of Microzooplankton at BOTTOM"
   var_units(268)="mmol N/m2/day"
   var_names(269)="jbotZ5p"
   var_long(269)="flux of Microzooplankton at BOTTOM"
   var_units(269)="mmol P/m2/day"
   var_names(270)="jbotZ6c"
   var_long(270)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(270)="mg C/m2/day"
   var_names(271)="jbotZ6n"
   var_long(271)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(271)="mmol N/m2/day"
   var_names(272)="jbotZ6p"
   var_long(272)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(272)="mmol P/m2/day"
   var_names(273)="jbotR1c"
   var_long(273)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(273)="mg C/m2/day"
   var_names(274)="jbotR1n"
   var_long(274)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(274)="mmol N/m2/day"
   var_names(275)="jbotR1p"
   var_long(275)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(275)="mmol P/m2/day"
   var_names(276)="jbotR2c"
   var_long(276)="flux of Semi-labile Dissolved Organic Carbon at BOTTOM"
   var_units(276)="mg C/m2/day"
   var_names(277)="jbotR3c"
   var_long(277)="flux of Semi-refractory Dissolved Organic Carbon at BOTTOM"
   var_units(277)="mg C/m2/day"
   var_names(278)="jbotR6c"
   var_long(278)="flux of Particulate Organic Matter at BOTTOM"
   var_units(278)="mg C/m2/day"
   var_names(279)="jbotR6n"
   var_long(279)="flux of Particulate Organic Matter at BOTTOM"
   var_units(279)="mmol N/m2/day"
   var_names(280)="jbotR6p"
   var_long(280)="flux of Particulate Organic Matter at BOTTOM"
   var_units(280)="mmol P/m2/day"
   var_names(281)="jbotR6s"
   var_long(281)="flux of Particulate Organic Matter at BOTTOM"
   var_units(281)="mmol Si/m2/day"
   var_names(282)="jbotO3c"
   var_long(282)="flux of Dissolved Inorganic Carbon at BOTTOM"
   var_units(282)="mg C/m2/day"
   var_names(283)="jbotO3h"
   var_long(283)="flux of Dissolved Inorganic Carbon at BOTTOM"
   var_units(283)="mmol eq/m2/day"

!
! river
!
   var_names(284)="jrivO2o"
   var_long(284)="flux of Oxygen at RIVER"
   var_units(284)="mmol O2/m2/day"
   var_names(285)="jrivN1p"
   var_long(285)="flux of Phosphate at RIVER"
   var_units(285)="mmol P/m2/day"
   var_names(286)="jrivN3n"
   var_long(286)="flux of Nitrate at RIVER"
   var_units(286)="mmol N/m2/day"
   var_names(287)="jrivN4n"
   var_long(287)="flux of Ammonium at RIVER"
   var_units(287)="mmol N/m2/day"
   var_names(288)="jrivO4n"
   var_long(288)="flux of NitrogenSink at RIVER"
   var_units(288)="mmol N/m2/day"
   var_names(289)="jrivN5s"
   var_long(289)="flux of Silicate at RIVER"
   var_units(289)="mmol Si/m2/day"
   var_names(290)="jrivN6r"
   var_long(290)="flux of Reduction Equivalents at RIVER"
   var_units(290)="mmol S--/m2/day"
   var_names(291)="jrivB1c"
   var_long(291)="flux of Aerobic and Anaerobic Bacteria at RIVER"
   var_units(291)="mg C/m2/day"
   var_names(292)="jrivB1n"
   var_long(292)="flux of Aerobic and Anaerobic Bacteria at RIVER"
   var_units(292)="mmol N/m2/day"
   var_names(293)="jrivB1p"
   var_long(293)="flux of Aerobic and Anaerobic Bacteria at RIVER"
   var_units(293)="mmol P/m2/day"
   var_names(294)="jrivP1c"
   var_long(294)="flux of Diatoms at RIVER"
   var_units(294)="mg C/m2/day"
   var_names(295)="jrivP1n"
   var_long(295)="flux of Diatoms at RIVER"
   var_units(295)="mmol N/m2/day"
   var_names(296)="jrivP1p"
   var_long(296)="flux of Diatoms at RIVER"
   var_units(296)="mmol P/m2/day"
   var_names(297)="jrivP1l"
   var_long(297)="flux of Diatoms at RIVER"
   var_units(297)="mg Chl/m2/day"
   var_names(298)="jrivP1s"
   var_long(298)="flux of Diatoms at RIVER"
   var_units(298)="mmol Si/m2/day"
   var_names(299)="jrivP2c"
   var_long(299)="flux of Flagellates at RIVER"
   var_units(299)="mg C/m2/day"
   var_names(300)="jrivP2n"
   var_long(300)="flux of Flagellates at RIVER"
   var_units(300)="mmol N/m2/day"
   var_names(301)="jrivP2p"
   var_long(301)="flux of Flagellates at RIVER"
   var_units(301)="mmol P/m2/day"
   var_names(302)="jrivP2l"
   var_long(302)="flux of Flagellates at RIVER"
   var_units(302)="mg Chl/m2/day"
   var_names(303)="jrivP3c"
   var_long(303)="flux of PicoPhytoplankton at RIVER"
   var_units(303)="mg C/m2/day"
   var_names(304)="jrivP3n"
   var_long(304)="flux of PicoPhytoplankton at RIVER"
   var_units(304)="mmol N/m2/day"
   var_names(305)="jrivP3p"
   var_long(305)="flux of PicoPhytoplankton at RIVER"
   var_units(305)="mmol P/m2/day"
   var_names(306)="jrivP3l"
   var_long(306)="flux of PicoPhytoplankton at RIVER"
   var_units(306)="mg Chl/m2/day"
   var_names(307)="jrivP4c"
   var_long(307)="flux of Large Phytoplankton at RIVER"
   var_units(307)="mg C/m2/day"
   var_names(308)="jrivP4n"
   var_long(308)="flux of Large Phytoplankton at RIVER"
   var_units(308)="mmol N/m2/day"
   var_names(309)="jrivP4p"
   var_long(309)="flux of Large Phytoplankton at RIVER"
   var_units(309)="mmol P/m2/day"
   var_names(310)="jrivP4l"
   var_long(310)="flux of Large Phytoplankton at RIVER"
   var_units(310)="mg Chl/m2/day"
   var_names(311)="jrivZ3c"
   var_long(311)="flux of Carnivorous Mesozooplankton at RIVER"
   var_units(311)="mg C/m2/day"
   var_names(312)="jrivZ3n"
   var_long(312)="flux of Carnivorous Mesozooplankton at RIVER"
   var_units(312)="mmol N/m2/day"
   var_names(313)="jrivZ3p"
   var_long(313)="flux of Carnivorous Mesozooplankton at RIVER"
   var_units(313)="mmol P/m2/day"
   var_names(314)="jrivZ4c"
   var_long(314)="flux of Omnivorous Mesozooplankton at RIVER"
   var_units(314)="mg C/m2/day"
   var_names(315)="jrivZ4n"
   var_long(315)="flux of Omnivorous Mesozooplankton at RIVER"
   var_units(315)="mmol N/m2/day"
   var_names(316)="jrivZ4p"
   var_long(316)="flux of Omnivorous Mesozooplankton at RIVER"
   var_units(316)="mmol P/m2/day"
   var_names(317)="jrivZ5c"
   var_long(317)="flux of Microzooplankton at RIVER"
   var_units(317)="mg C/m2/day"
   var_names(318)="jrivZ5n"
   var_long(318)="flux of Microzooplankton at RIVER"
   var_units(318)="mmol N/m2/day"
   var_names(319)="jrivZ5p"
   var_long(319)="flux of Microzooplankton at RIVER"
   var_units(319)="mmol P/m2/day"
   var_names(320)="jrivZ6c"
   var_long(320)="flux of Heterotrophic Nanoflagellates (HNAN) at RIVER"
   var_units(320)="mg C/m2/day"
   var_names(321)="jrivZ6n"
   var_long(321)="flux of Heterotrophic Nanoflagellates (HNAN) at RIVER"
   var_units(321)="mmol N/m2/day"
   var_names(322)="jrivZ6p"
   var_long(322)="flux of Heterotrophic Nanoflagellates (HNAN) at RIVER"
   var_units(322)="mmol P/m2/day"
   var_names(323)="jrivR1c"
   var_long(323)="flux of Labile Dissolved Organic Matter at RIVER"
   var_units(323)="mg C/m2/day"
   var_names(324)="jrivR1n"
   var_long(324)="flux of Labile Dissolved Organic Matter at RIVER"
   var_units(324)="mmol N/m2/day"
   var_names(325)="jrivR1p"
   var_long(325)="flux of Labile Dissolved Organic Matter at RIVER"
   var_units(325)="mmol P/m2/day"
   var_names(326)="jrivR2c"
   var_long(326)="flux of Semi-labile Dissolved Organic Carbon at RIVER"
   var_units(326)="mg C/m2/day"
   var_names(327)="jrivR3c"
   var_long(327)="flux of Semi-refractory Dissolved Organic Carbon at RIVER"
   var_units(327)="mg C/m2/day"
   var_names(328)="jrivR6c"
   var_long(328)="flux of Particulate Organic Matter at RIVER"
   var_units(328)="mg C/m2/day"
   var_names(329)="jrivR6n"
   var_long(329)="flux of Particulate Organic Matter at RIVER"
   var_units(329)="mmol N/m2/day"
   var_names(330)="jrivR6p"
   var_long(330)="flux of Particulate Organic Matter at RIVER"
   var_units(330)="mmol P/m2/day"
   var_names(331)="jrivR6s"
   var_long(331)="flux of Particulate Organic Matter at RIVER"
   var_units(331)="mmol Si/m2/day"
   var_names(332)="jrivO3c"
   var_long(332)="flux of Dissolved Inorganic Carbon at RIVER"
   var_units(332)="mg C/m2/day"
   var_names(333)="jrivO3h"
   var_long(333)="flux of Dissolved Inorganic Carbon at RIVER"
   var_units(333)="mmol eq/m2/day"


#ifdef INCLUDE_SEAICE
!
!2d SeaIce variables description




#endif

#ifdef INCLUDE_BEN
!
!2d Benthic variables description




#endif


!
!Index Pelagic
!
   stPelStart=1
   stPelEnd=333


   stPelStateS=1
   stPelStateE=50

   stPelDiagS=51
   stPelDiagE=141

   stPelFluxS=142
   stPelFluxE=171

   stPelDiag2dS=172
   stPelDiag2dE=183

   stPelSurS=184
   stPelSurE=233

   stPelBotS=234
   stPelBotE=283

   stPelRivS=284
   stPelRivE=333



#ifdef INCLUDE_SEAICE
!
!Index SeaIce
!
   stIceStart=334
   stIceEnd=333


   stIceStateS=334
   stIceStateE=333

   stIceDiag2dS=334
   stIceDiag2dE=333

   stIceFlux2dS=334
   stIceFlux2dE=333


#endif

#ifdef INCLUDE_BEN
!
!Index Benthic
!
   stBenStart=334
   stBenEnd=333


   stBenStateS=334
   stBenStateE=333

   stBenDiag2dS=334
   stBenDiag2dE=333

   stBenFlux2dS=334
   stBenFlux2dE=333


#endif


   stStart=1
   stEnd=333


end subroutine set_var_info_bfm
